/**
 * Additional world-cuisine seed foods + metadata fields.
 * Nutrients are approximate per serving for wellness tracking.
 */

const emptyMicro = {
  calories: 0, protein: 0, carbs: 0, fiber: 0, fat: 0, saturatedFat: 0, omega3: 0, cholesterol: 0,
  potassium: 0, magnesium: 0, calcium: 0, zinc: 0, iron: 0, sodium: 0,
  vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0, vitaminK: 0,
  b1: 0, b2: 0, b3: 0, b5: 0, b6: 0, b7: 0, b9: 0, b12: 0, choline: 0, creatine: 0, probiotics: 0, waterMl: 0,
}

const WORLD_SEED_FOODS = [
  {
    name: 'Laban (yogurt drink)',
    serving_unit: 'ml', serving_size: 200,
    tags: ['probiotics', 'world_diet', 'uae'],
    origin_region: 'middle_eastern',
    diet_tags: ['world_diet', 'middle_eastern', 'budget_friendly'],
    nutrient_tags: ['probiotic', 'fermented', 'high_protein', 'calcium', 'hydration'],
    caution_tags: ['allergen_dairy'],
    why_recommended: 'Traditional fermented dairy drink with protein and calcium — supports probiotic variety.',
    nutrients: { ...emptyMicro, calories: 80, protein: 6, carbs: 8, fat: 2.5, saturatedFat: 1.6, calcium: 180, potassium: 220, probiotics: 1, waterMl: 170 },
  },
  {
    name: 'Lentil soup (traditional)',
    serving_unit: 'g', serving_size: 250,
    tags: ['protein', 'fiber', 'world_diet'],
    origin_region: 'middle_eastern',
    diet_tags: ['world_diet', 'middle_eastern', 'budget_friendly'],
    nutrient_tags: ['high_protein', 'fiber', 'iron', 'slow_carb', 'minerals'],
    caution_tags: [],
    why_recommended: 'Legume soup with fiber and plant protein — a staple in many Middle Eastern and global diets.',
    nutrients: { ...emptyMicro, calories: 180, protein: 12, carbs: 28, fiber: 8, fat: 3, iron: 3.5, potassium: 420, magnesium: 45, b9: 90 },
  },
  {
    name: 'Parsley (fresh)',
    serving_unit: 'g', serving_size: 10,
    tags: ['vegetables', 'world_diet'],
    origin_region: 'middle_eastern',
    diet_tags: ['world_diet', 'middle_eastern'],
    nutrient_tags: ['vitamin_c', 'iron', 'anti_inflammatory', 'herbs_spices'],
    caution_tags: [],
    why_recommended: 'Fresh herb adding vitamin C and flavor without many calories.',
    nutrients: { ...emptyMicro, calories: 4, protein: 0.3, carbs: 0.6, fiber: 0.3, vitaminC: 13, vitaminK: 164, iron: 0.9, potassium: 55 },
  },
  {
    name: 'Dal (lentil curry)',
    serving_unit: 'g', serving_size: 200,
    tags: ['protein', 'fiber', 'world_diet'],
    origin_region: 'south_asian',
    diet_tags: ['world_diet', 'south_asian', 'budget_friendly', 'vegetarian'],
    nutrient_tags: ['high_protein', 'fiber', 'iron', 'slow_carb', 'minerals', 'anti_inflammatory'],
    caution_tags: [],
    why_recommended: 'South Asian lentil dish — fiber, plant protein, and minerals from legumes and spices.',
    nutrients: { ...emptyMicro, calories: 210, protein: 13, carbs: 32, fiber: 9, fat: 4, iron: 3.8, potassium: 480, magnesium: 50, b9: 120 },
  },
  {
    name: 'Lassi (yogurt drink)',
    serving_unit: 'ml', serving_size: 200,
    tags: ['probiotics', 'world_diet'],
    origin_region: 'south_asian',
    diet_tags: ['world_diet', 'south_asian'],
    nutrient_tags: ['probiotic', 'fermented', 'calcium', 'hydration'],
    caution_tags: ['allergen_dairy'],
    why_recommended: 'Yogurt-based drink with probiotics and calcium — traditional hydration and dairy culture food.',
    nutrients: { ...emptyMicro, calories: 120, protein: 5, carbs: 16, fat: 4, calcium: 150, probiotics: 1, waterMl: 160 },
  },
  {
    name: 'Turmeric (ground)',
    serving_unit: 'g', serving_size: 2,
    tags: ['herbs_spices', 'world_diet'],
    origin_region: 'south_asian',
    diet_tags: ['world_diet', 'south_asian'],
    nutrient_tags: ['herbs_spices', 'anti_inflammatory', 'iron'],
    caution_tags: [],
    why_recommended: 'Traditional spice used in many cuisines — adds flavor; research links curcumin to anti-inflammatory pathways (not a cure).',
    nutrients: { ...emptyMicro, calories: 6, protein: 0.2, carbs: 1.3, fiber: 0.4, iron: 0.5, potassium: 33 },
  },
  {
    name: 'Ginger (fresh)',
    serving_unit: 'g', serving_size: 10,
    tags: ['herbs_spices', 'world_diet'],
    origin_region: 'south_asian',
    diet_tags: ['world_diet', 'south_asian', 'global'],
    nutrient_tags: ['herbs_spices', 'anti_inflammatory'],
    caution_tags: [],
    why_recommended: 'Aromatic root used globally — adds flavor with minimal calories.',
    nutrients: { ...emptyMicro, calories: 8, protein: 0.2, carbs: 1.8, fiber: 0.2, potassium: 42, magnesium: 4, vitaminC: 0.5 },
  },
  {
    name: 'Garlic (fresh)',
    serving_unit: 'g', serving_size: 5,
    tags: ['herbs_spices', 'world_diet'],
    origin_region: 'global',
    diet_tags: ['world_diet', 'global', 'budget_friendly'],
    nutrient_tags: ['herbs_spices', 'anti_inflammatory'],
    caution_tags: [],
    why_recommended: 'Used across cultures for flavor; contains sulfur compounds studied for cardiovascular support (not a treatment).',
    nutrients: { ...emptyMicro, calories: 7, protein: 0.3, carbs: 1.5, fiber: 0.1, manganese: 0.1, vitaminC: 1, b6: 0.04 },
  },
  {
    name: 'Miso soup',
    serving_unit: 'g', serving_size: 200,
    tags: ['probiotics', 'world_diet'],
    origin_region: 'japanese',
    diet_tags: ['world_diet', 'japanese'],
    nutrient_tags: ['fermented', 'probiotic', 'high_protein', 'minerals'],
    caution_tags: ['high_sodium', 'allergen_soy'],
    why_recommended: 'Fermented soybean soup — probiotics and umami; watch sodium in portions.',
    nutrients: { ...emptyMicro, calories: 70, protein: 5, carbs: 8, fat: 2, sodium: 780, probiotics: 1, waterMl: 170 },
  },
  {
    name: 'Natto (fermented soybeans)',
    serving_unit: 'g', serving_size: 50,
    tags: ['probiotics', 'world_diet'],
    origin_region: 'japanese',
    diet_tags: ['world_diet', 'japanese', 'vegetarian'],
    nutrient_tags: ['fermented', 'probiotic', 'high_protein', 'vitamin_k', 'iron'],
    caution_tags: ['allergen_soy'],
    why_recommended: 'Traditional fermented soy with protein, vitamin K, and live cultures.',
    nutrients: { ...emptyMicro, calories: 105, protein: 9, carbs: 7, fiber: 3, fat: 5, iron: 2.5, vitaminK: 850, probiotics: 1 },
  },
  {
    name: 'Tofu (firm)',
    serving_unit: 'g', serving_size: 100,
    tags: ['protein', 'world_diet'],
    origin_region: 'japanese',
    diet_tags: ['world_diet', 'japanese', 'korean', 'vegetarian', 'budget_friendly'],
    nutrient_tags: ['high_protein', 'calcium', 'iron'],
    caution_tags: ['allergen_soy'],
    why_recommended: 'Soy protein staple in East Asian diets — versatile plant protein source.',
    nutrients: { ...emptyMicro, calories: 144, protein: 15, carbs: 3, fat: 8, saturatedFat: 1.2, calcium: 350, iron: 2.7, magnesium: 37 },
  },
  {
    name: 'Seaweed (nori)',
    serving_unit: 'g', serving_size: 5,
    tags: ['world_diet'],
    origin_region: 'japanese',
    diet_tags: ['world_diet', 'japanese', 'korean'],
    nutrient_tags: ['minerals', 'iodine', 'iron', 'anti_inflammatory'],
    caution_tags: ['high_sodium'],
    why_recommended: 'Mineral-rich sea vegetable — iodine and trace minerals; use modest portions.',
    nutrients: { ...emptyMicro, calories: 10, protein: 1, carbs: 1, fiber: 0.5, iron: 0.5, sodium: 50, vitaminC: 2, vitaminA: 50 },
  },
  {
    name: 'Green tea',
    serving_unit: 'ml', serving_size: 240,
    tags: ['hydration', 'world_diet'],
    origin_region: 'japanese',
    diet_tags: ['world_diet', 'japanese', 'global'],
    nutrient_tags: ['hydration', 'antioxidant_rich', 'anti_inflammatory'],
    caution_tags: [],
    why_recommended: 'Traditional unsweetened drink with antioxidants — hydration without added sugar.',
    nutrients: { ...emptyMicro, calories: 2, waterMl: 238 },
  },
  {
    name: 'Kimchi',
    serving_unit: 'g', serving_size: 100,
    tags: ['probiotics', 'world_diet'],
    origin_region: 'korean',
    diet_tags: ['world_diet', 'korean', 'budget_friendly'],
    nutrient_tags: ['fermented', 'probiotic', 'fiber', 'vitamin_c', 'anti_inflammatory'],
    caution_tags: ['high_sodium'],
    why_recommended: 'Fermented vegetables with fiber and live cultures — portion control for sodium.',
    nutrients: { ...emptyMicro, calories: 24, protein: 1.5, carbs: 4, fiber: 2, fat: 0.5, sodium: 670, vitaminC: 14, probiotics: 1 },
  },
  {
    name: 'Rye bread',
    serving_unit: 'g', serving_size: 40,
    tags: ['carbs', 'world_diet'],
    origin_region: 'nordic',
    diet_tags: ['world_diet', 'nordic'],
    nutrient_tags: ['slow_carb', 'fiber', 'minerals'],
    caution_tags: ['allergen_gluten'],
    why_recommended: 'Whole-grain Nordic staple with more fiber than refined bread.',
    nutrients: { ...emptyMicro, calories: 95, protein: 3.5, carbs: 18, fiber: 3.5, fat: 1, iron: 1, magnesium: 20 },
  },
  {
    name: 'Mixed berries',
    serving_unit: 'g', serving_size: 100,
    tags: ['world_diet'],
    origin_region: 'nordic',
    diet_tags: ['world_diet', 'nordic', 'global'],
    nutrient_tags: ['antioxidant_rich', 'fiber', 'vitamin_c', 'low_glycemic'],
    caution_tags: [],
    why_recommended: 'Berries provide fiber and vitamin C with relatively low glycemic impact.',
    nutrients: { ...emptyMicro, calories: 57, protein: 0.7, carbs: 14, fiber: 2.4, vitaminC: 20, potassium: 77 },
  },
  {
    name: 'Corn (cooked)',
    serving_unit: 'g', serving_size: 100,
    tags: ['carbs', 'world_diet'],
    origin_region: 'latin',
    diet_tags: ['world_diet', 'latin', 'budget_friendly'],
    nutrient_tags: ['slow_carb', 'fiber', 'minerals'],
    caution_tags: [],
    why_recommended: 'Traditional Latin American staple carb with fiber and B vitamins.',
    nutrients: { ...emptyMicro, calories: 96, protein: 3.4, carbs: 21, fiber: 2.4, fat: 1.5, potassium: 270, b9: 42 },
  },
  {
    name: 'Quinoa (cooked)',
    serving_unit: 'g', serving_size: 100,
    tags: ['protein', 'fiber', 'world_diet'],
    origin_region: 'latin',
    diet_tags: ['world_diet', 'latin', 'global', 'vegetarian'],
    nutrient_tags: ['high_protein', 'fiber', 'slow_carb', 'iron', 'magnesium'],
    caution_tags: [],
    why_recommended: 'Andean whole grain with complete plant protein and minerals.',
    nutrients: { ...emptyMicro, calories: 120, protein: 4.4, carbs: 21, fiber: 2.8, fat: 1.9, iron: 1.5, magnesium: 64, potassium: 172 },
  },
  {
    name: 'Salsa (fresh tomato)',
    serving_unit: 'g', serving_size: 50,
    tags: ['vegetables', 'world_diet'],
    origin_region: 'latin',
    diet_tags: ['world_diet', 'latin', 'budget_friendly'],
    nutrient_tags: ['vitamin_c', 'anti_inflammatory', 'hydration'],
    caution_tags: [],
    why_recommended: 'Fresh tomato-based condiment adding vegetables and vitamin C with few calories.',
    nutrients: { ...emptyMicro, calories: 15, protein: 0.5, carbs: 3, fiber: 0.8, vitaminC: 8, potassium: 120, waterMl: 42 },
  },
  {
    name: 'Millet (cooked)',
    serving_unit: 'g', serving_size: 100,
    tags: ['carbs', 'world_diet'],
    origin_region: 'african',
    diet_tags: ['world_diet', 'african', 'budget_friendly', 'vegetarian'],
    nutrient_tags: ['slow_carb', 'magnesium', 'iron', 'fiber'],
    caution_tags: [],
    why_recommended: 'African heritage grain with magnesium and slow-digesting carbs.',
    nutrients: { ...emptyMicro, calories: 119, protein: 3.5, carbs: 23, fiber: 1.3, fat: 1, magnesium: 44, iron: 0.6, potassium: 62 },
  },
  {
    name: 'Sorghum (cooked)',
    serving_unit: 'g', serving_size: 100,
    tags: ['carbs', 'world_diet'],
    origin_region: 'african',
    diet_tags: ['world_diet', 'african', 'budget_friendly', 'vegetarian'],
    nutrient_tags: ['slow_carb', 'iron', 'fiber', 'minerals'],
    caution_tags: [],
    why_recommended: 'Traditional African grain — gluten-free whole grain option with iron and fiber.',
    nutrients: { ...emptyMicro, calories: 97, protein: 3, carbs: 21, fiber: 2.5, fat: 1, iron: 1.2, magnesium: 28 },
  },
  {
    name: 'Leafy greens (mixed)',
    serving_unit: 'g', serving_size: 100,
    tags: ['vegetables', 'world_diet'],
    origin_region: 'african',
    diet_tags: ['world_diet', 'african', 'global', 'budget_friendly', 'vegetarian'],
    nutrient_tags: ['iron', 'fiber', 'vitamin_c', 'minerals', 'anti_inflammatory'],
    caution_tags: [],
    why_recommended: 'Leafy greens across cultures provide iron, folate, and fiber with low calories.',
    nutrients: { ...emptyMicro, calories: 25, protein: 2.5, carbs: 4, fiber: 2, iron: 2, vitaminC: 30, vitaminK: 200, b9: 80, potassium: 300 },
  },
  {
    name: 'Apple',
    serving_unit: 'g', serving_size: 100,
    tags: ['world_diet', 'fruits'],
    origin_region: 'global',
    diet_tags: ['world_diet', 'global', 'vegetarian', 'budget_friendly'],
    nutrient_tags: ['fiber', 'vitamin_c', 'slow_carb', 'hydration'],
    caution_tags: [],
    why_recommended: 'Common fruit with fiber and vitamin C — useful slow carb snack.',
    nutrients: { ...emptyMicro, calories: 52, protein: 0.3, carbs: 14, fiber: 2.4, fat: 0.2, vitaminC: 4.6, potassium: 107, b9: 3, waterMl: 86 },
  },
  {
    name: 'Granola',
    serving_unit: 'g', serving_size: 50,
    tags: ['world_diet', 'carbs', 'fiber'],
    origin_region: 'global',
    diet_tags: ['world_diet', 'global', 'vegetarian'],
    nutrient_tags: ['slow_carb', 'fiber', 'magnesium', 'healthy_fats'],
    caution_tags: ['calorie_dense'],
    why_recommended: 'Oats/nuts mix with fiber and energy — measure portions due to calorie density.',
    nutrients: { ...emptyMicro, calories: 240, protein: 6, carbs: 32, fiber: 4, fat: 10, saturatedFat: 2, magnesium: 45, iron: 1.5, potassium: 180 },
  },
  {
    name: 'Bitter gourd (karela)',
    serving_unit: 'g', serving_size: 100,
    tags: ['world_diet', 'vegetables'],
    origin_region: 'south_asian',
    diet_tags: ['world_diet', 'south_asian', 'vegetarian', 'budget_friendly'],
    nutrient_tags: ['fiber', 'vitamin_c', 'low_glycemic', 'anti_inflammatory'],
    caution_tags: [],
    why_recommended: 'South Asian vegetable low in calories with fiber and vitamin C.',
    nutrients: { ...emptyMicro, calories: 17, protein: 1, carbs: 3.7, fiber: 2.8, fat: 0.2, vitaminC: 33, vitaminA: 24, potassium: 296, iron: 0.4, waterMl: 87 },
  },
]

module.exports = { WORLD_SEED_FOODS }
