/** Common options for nationality field (datalist); free text still allowed. */
export const NATIONALITY_SUGGESTIONS = [
  'United Arab Emirates',
  'India',
  'Pakistan',
  'Philippines',
  'Egypt',
  'United Kingdom',
  'United States',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'Sudan',
  'Jordan',
  'Lebanon',
  'Iran',
  'Iraq',
  'Afghanistan',
  'Nigeria',
  'Kenya',
  'Ethiopia',
  'China',
  'Russia',
  'France',
  'Germany',
  'Canada',
  'Australia',
]
