/**
 * Central Amazon SP-API pacing and sync limits (no secrets).
 * Tune here first; wire callers to these exports instead of duplicating literals.
 */

const GET_ORDERS_MIN_INTERVAL_MS = 70_000
const GET_ORDER_ITEMS_MIN_INTERVAL_MS = 2200
const GET_MARKETPLACE_PARTICIPATIONS_MIN_INTERVAL_MS = 45_000
const CATALOG_SEARCH_MIN_INTERVAL_MS = 3000
const FBA_INVENTORY_MIN_INTERVAL_MS = 2500
const REPORTS_MIN_INTERVAL_MS = 2500
const MANUAL_SYNC_COOLDOWN_MINUTES = 10
const MAX_SYNC_RANGE_DAYS = 7
const MAX_ORDER_ITEMS_ENRICH_PER_SYNC = 100
const MAX_CATALOG_IMAGE_ASINS_PER_REQUEST = 20
/** Max Search Catalog Items batches per HTTP request (e.g. orders page with limit 200). Each batch respects rate spacing. */
const MAX_CATALOG_IMAGE_ENRICHMENT_BATCHES = 15
const MAX_AMAZON_RETRIES = 3

/** Milliseconds before "now" used as CreatedBefore upper bound (avoid in-flight orders). */
const SYNC_CREATED_BEFORE_BUFFER_MS = 130_000

module.exports = {
  GET_ORDERS_MIN_INTERVAL_MS,
  GET_ORDER_ITEMS_MIN_INTERVAL_MS,
  GET_MARKETPLACE_PARTICIPATIONS_MIN_INTERVAL_MS,
  CATALOG_SEARCH_MIN_INTERVAL_MS,
  FBA_INVENTORY_MIN_INTERVAL_MS,
  REPORTS_MIN_INTERVAL_MS,
  MANUAL_SYNC_COOLDOWN_MINUTES,
  MAX_SYNC_RANGE_DAYS,
  MAX_ORDER_ITEMS_ENRICH_PER_SYNC,
  MAX_CATALOG_IMAGE_ASINS_PER_REQUEST,
  MAX_CATALOG_IMAGE_ENRICHMENT_BATCHES,
  MAX_AMAZON_RETRIES,
  SYNC_CREATED_BEFORE_BUFFER_MS,
}
